// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace loki {
    
    
    public partial class AddJobWin {
        
        private Gtk.Alignment alignmentWindow;
        
        private Gtk.VBox vboxWindow;
        
        private Gtk.Alignment alignmentGeneral;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment alignment22;
        
        private Gtk.VBox vbox16;
        
        private Gtk.HBox hbox28;
        
        private Gtk.Label label25;
        
        private Gtk.ComboBox cBoxType;
        
        private Gtk.HBox hbox26;
        
        private Gtk.Label label23;
        
        private Gtk.Entry eName;
        
        private Gtk.Label GtkLabel;
        
        private Gtk.Alignment alignmentWindows;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment alignment21;
        
        private Gtk.VBox vbox15;
        
        private Gtk.HBox hbox25;
        
        private Gtk.Label label22;
        
        private Gtk.Entry eWinFile;
        
        private Gtk.HBox hbox24;
        
        private Gtk.Label label21;
        
        private Gtk.Entry eWinOutputDir;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Alignment alignmentUnix;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment alignment20;
        
        private Gtk.VBox vbox14;
        
        private Gtk.HBox hbox22;
        
        private Gtk.Label label19;
        
        private Gtk.Entry eUnixFile;
        
        private Gtk.HBox hbox23;
        
        private Gtk.Label label20;
        
        private Gtk.Entry eUnixOutputDir;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.Alignment alignmentFrames;
        
        private Gtk.Frame frame6;
        
        private Gtk.Alignment alignment19;
        
        private Gtk.VBox vbox13;
        
        private Gtk.HBox hbox20;
        
        private Gtk.Label label17;
        
        private Gtk.Entry eFirstFrame;
        
        private Gtk.HBox hbox21;
        
        private Gtk.Label label18;
        
        private Gtk.Entry eLastFrame;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Alignment alignmentButtons;
        
        private Gtk.HBox hboxButtons;
        
        private Gtk.HBox hbox10;
        
        private Gtk.Button btnCancel;
        
        private Gtk.Button btnSave;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget loki.AddJobWin
            this.Name = "loki.AddJobWin";
            this.Title = "Job";
            this.Icon = Gdk.Pixbuf.LoadFromResource("16x16.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            // Container child loki.AddJobWin.Gtk.Container+ContainerChild
            this.alignmentWindow = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignmentWindow.Name = "alignmentWindow";
            this.alignmentWindow.BorderWidth = ((uint)(10));
            // Container child alignmentWindow.Gtk.Container+ContainerChild
            this.vboxWindow = new Gtk.VBox();
            this.vboxWindow.Name = "vboxWindow";
            this.vboxWindow.Spacing = 6;
            // Container child vboxWindow.Gtk.Box+BoxChild
            this.alignmentGeneral = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignmentGeneral.Name = "alignmentGeneral";
            // Container child alignmentGeneral.Gtk.Container+ContainerChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame3.Gtk.Container+ContainerChild
            this.alignment22 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment22.Name = "alignment22";
            this.alignment22.BorderWidth = ((uint)(8));
            // Container child alignment22.Gtk.Container+ContainerChild
            this.vbox16 = new Gtk.VBox();
            this.vbox16.Name = "vbox16";
            this.vbox16.Spacing = 6;
            // Container child vbox16.Gtk.Box+BoxChild
            this.hbox28 = new Gtk.HBox();
            this.hbox28.Name = "hbox28";
            this.hbox28.Spacing = 6;
            // Container child hbox28.Gtk.Box+BoxChild
            this.label25 = new Gtk.Label();
            this.label25.WidthRequest = 100;
            this.label25.Name = "label25";
            this.label25.Xalign = 1F;
            this.label25.LabelProp = "Type:";
            this.hbox28.Add(this.label25);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox28[this.label25]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox28.Gtk.Box+BoxChild
            this.cBoxType = Gtk.ComboBox.NewText();
            this.cBoxType.AppendText("Blender");
            this.cBoxType.TooltipMarkup = "Type of job, e.g. 'Blender'";
            this.cBoxType.Name = "cBoxType";
            this.cBoxType.Active = 0;
            this.hbox28.Add(this.cBoxType);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox28[this.cBoxType]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.vbox16.Add(this.hbox28);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox16[this.hbox28]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox16.Gtk.Box+BoxChild
            this.hbox26 = new Gtk.HBox();
            this.hbox26.Name = "hbox26";
            this.hbox26.Spacing = 6;
            // Container child hbox26.Gtk.Box+BoxChild
            this.label23 = new Gtk.Label();
            this.label23.WidthRequest = 100;
            this.label23.Name = "label23";
            this.label23.Xalign = 1F;
            this.label23.LabelProp = "Name:";
            this.hbox26.Add(this.label23);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox26[this.label23]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox26.Gtk.Box+BoxChild
            this.eName = new Gtk.Entry();
            this.eName.TooltipMarkup = "An arbitrary name that you choose for the job, e.g. 'rabbit-scene1_2'";
            this.eName.CanFocus = true;
            this.eName.Name = "eName";
            this.eName.IsEditable = true;
            this.eName.InvisibleChar = '●';
            this.hbox26.Add(this.eName);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox26[this.eName]));
            w5.Position = 1;
            this.vbox16.Add(this.hbox26);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox16[this.hbox26]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.alignment22.Add(this.vbox16);
            this.frame3.Add(this.alignment22);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = "<b>General</b>";
            this.GtkLabel.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel;
            this.alignmentGeneral.Add(this.frame3);
            this.vboxWindow.Add(this.alignmentGeneral);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vboxWindow[this.alignmentGeneral]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vboxWindow.Gtk.Box+BoxChild
            this.alignmentWindows = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignmentWindows.Name = "alignmentWindows";
            // Container child alignmentWindows.Gtk.Container+ContainerChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame4.Gtk.Container+ContainerChild
            this.alignment21 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment21.Name = "alignment21";
            this.alignment21.BorderWidth = ((uint)(8));
            // Container child alignment21.Gtk.Container+ContainerChild
            this.vbox15 = new Gtk.VBox();
            this.vbox15.Name = "vbox15";
            this.vbox15.Spacing = 6;
            // Container child vbox15.Gtk.Box+BoxChild
            this.hbox25 = new Gtk.HBox();
            this.hbox25.Name = "hbox25";
            this.hbox25.Spacing = 6;
            // Container child hbox25.Gtk.Box+BoxChild
            this.label22 = new Gtk.Label();
            this.label22.WidthRequest = 100;
            this.label22.Name = "label22";
            this.label22.Xalign = 1F;
            this.label22.LabelProp = "Blend file:";
            this.hbox25.Add(this.label22);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox25[this.label22]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox25.Gtk.Box+BoxChild
            this.eWinFile = new Gtk.Entry();
            this.eWinFile.TooltipMarkup = "Windows style path to the blend file, e.g. 'X:\\loki\\rabbitProj\\rabbit.blend'";
            this.eWinFile.CanFocus = true;
            this.eWinFile.Name = "eWinFile";
            this.eWinFile.IsEditable = true;
            this.eWinFile.InvisibleChar = '●';
            this.hbox25.Add(this.eWinFile);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox25[this.eWinFile]));
            w12.Position = 1;
            this.vbox15.Add(this.hbox25);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox15[this.hbox25]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox15.Gtk.Box+BoxChild
            this.hbox24 = new Gtk.HBox();
            this.hbox24.Name = "hbox24";
            this.hbox24.Spacing = 6;
            // Container child hbox24.Gtk.Box+BoxChild
            this.label21 = new Gtk.Label();
            this.label21.WidthRequest = 100;
            this.label21.Name = "label21";
            this.label21.Xalign = 1F;
            this.label21.LabelProp = "Output dir:";
            this.hbox24.Add(this.label21);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox24[this.label21]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child hbox24.Gtk.Box+BoxChild
            this.eWinOutputDir = new Gtk.Entry();
            this.eWinOutputDir.TooltipMarkup = "Windows style path where the rendered frames will be placed. Make sure you have a trailing slash, e.g. 'X:\\loki\\rabbitProj\\output\\scene1_2\\'";
            this.eWinOutputDir.CanFocus = true;
            this.eWinOutputDir.Name = "eWinOutputDir";
            this.eWinOutputDir.IsEditable = true;
            this.eWinOutputDir.InvisibleChar = '●';
            this.hbox24.Add(this.eWinOutputDir);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox24[this.eWinOutputDir]));
            w15.Position = 1;
            this.vbox15.Add(this.hbox24);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox15[this.hbox24]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            this.alignment21.Add(this.vbox15);
            this.frame4.Add(this.alignment21);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = "<b>Windows style paths</b>";
            this.GtkLabel1.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel1;
            this.alignmentWindows.Add(this.frame4);
            this.vboxWindow.Add(this.alignmentWindows);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vboxWindow[this.alignmentWindows]));
            w20.Position = 1;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vboxWindow.Gtk.Box+BoxChild
            this.alignmentUnix = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignmentUnix.Name = "alignmentUnix";
            // Container child alignmentUnix.Gtk.Container+ContainerChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame5.Gtk.Container+ContainerChild
            this.alignment20 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment20.Name = "alignment20";
            this.alignment20.BorderWidth = ((uint)(8));
            // Container child alignment20.Gtk.Container+ContainerChild
            this.vbox14 = new Gtk.VBox();
            this.vbox14.Name = "vbox14";
            this.vbox14.Spacing = 6;
            // Container child vbox14.Gtk.Box+BoxChild
            this.hbox22 = new Gtk.HBox();
            this.hbox22.Name = "hbox22";
            this.hbox22.Spacing = 6;
            // Container child hbox22.Gtk.Box+BoxChild
            this.label19 = new Gtk.Label();
            this.label19.WidthRequest = 100;
            this.label19.Name = "label19";
            this.label19.Xalign = 1F;
            this.label19.LabelProp = "Blend file:";
            this.hbox22.Add(this.label19);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox22[this.label19]));
            w21.Position = 0;
            w21.Expand = false;
            w21.Fill = false;
            // Container child hbox22.Gtk.Box+BoxChild
            this.eUnixFile = new Gtk.Entry();
            this.eUnixFile.TooltipMarkup = "Unix style path to the blend file, e.g. '/mnt/loki/rabbitProj/rabbit.blend'";
            this.eUnixFile.CanFocus = true;
            this.eUnixFile.Name = "eUnixFile";
            this.eUnixFile.IsEditable = true;
            this.eUnixFile.InvisibleChar = '●';
            this.hbox22.Add(this.eUnixFile);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox22[this.eUnixFile]));
            w22.Position = 1;
            this.vbox14.Add(this.hbox22);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox14[this.hbox22]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox14.Gtk.Box+BoxChild
            this.hbox23 = new Gtk.HBox();
            this.hbox23.Name = "hbox23";
            this.hbox23.Spacing = 6;
            // Container child hbox23.Gtk.Box+BoxChild
            this.label20 = new Gtk.Label();
            this.label20.WidthRequest = 100;
            this.label20.Name = "label20";
            this.label20.Xalign = 1F;
            this.label20.LabelProp = "Output dir:";
            this.hbox23.Add(this.label20);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox23[this.label20]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            // Container child hbox23.Gtk.Box+BoxChild
            this.eUnixOutputDir = new Gtk.Entry();
            this.eUnixOutputDir.TooltipMarkup = "Unix style path where the rendered frames will be placed. Make sure you have a trailing slash, e.g. '/mnt/loki/rabbitProj/output/scene1_2/'";
            this.eUnixOutputDir.CanFocus = true;
            this.eUnixOutputDir.Name = "eUnixOutputDir";
            this.eUnixOutputDir.IsEditable = true;
            this.eUnixOutputDir.InvisibleChar = '●';
            this.hbox23.Add(this.eUnixOutputDir);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox23[this.eUnixOutputDir]));
            w25.Position = 1;
            this.vbox14.Add(this.hbox23);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox14[this.hbox23]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            this.alignment20.Add(this.vbox14);
            this.frame5.Add(this.alignment20);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = "<b>Unix style paths</b>";
            this.GtkLabel2.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel2;
            this.alignmentUnix.Add(this.frame5);
            this.vboxWindow.Add(this.alignmentUnix);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.vboxWindow[this.alignmentUnix]));
            w30.Position = 2;
            w30.Expand = false;
            w30.Fill = false;
            // Container child vboxWindow.Gtk.Box+BoxChild
            this.alignmentFrames = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignmentFrames.Name = "alignmentFrames";
            // Container child alignmentFrames.Gtk.Container+ContainerChild
            this.frame6 = new Gtk.Frame();
            this.frame6.Name = "frame6";
            this.frame6.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame6.Gtk.Container+ContainerChild
            this.alignment19 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment19.Name = "alignment19";
            this.alignment19.BorderWidth = ((uint)(8));
            // Container child alignment19.Gtk.Container+ContainerChild
            this.vbox13 = new Gtk.VBox();
            this.vbox13.Name = "vbox13";
            this.vbox13.Spacing = 6;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox20 = new Gtk.HBox();
            this.hbox20.Name = "hbox20";
            this.hbox20.Spacing = 6;
            // Container child hbox20.Gtk.Box+BoxChild
            this.label17 = new Gtk.Label();
            this.label17.WidthRequest = 100;
            this.label17.Name = "label17";
            this.label17.Xalign = 1F;
            this.label17.LabelProp = "First frame:";
            this.hbox20.Add(this.label17);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox20[this.label17]));
            w31.Position = 0;
            w31.Expand = false;
            w31.Fill = false;
            // Container child hbox20.Gtk.Box+BoxChild
            this.eFirstFrame = new Gtk.Entry();
            this.eFirstFrame.TooltipMarkup = "First frame in the range of frames to be rendered, e.g. '1'";
            this.eFirstFrame.CanFocus = true;
            this.eFirstFrame.Name = "eFirstFrame";
            this.eFirstFrame.IsEditable = true;
            this.eFirstFrame.InvisibleChar = '●';
            this.hbox20.Add(this.eFirstFrame);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox20[this.eFirstFrame]));
            w32.Position = 1;
            this.vbox13.Add(this.hbox20);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox13[this.hbox20]));
            w33.Position = 0;
            w33.Expand = false;
            w33.Fill = false;
            // Container child vbox13.Gtk.Box+BoxChild
            this.hbox21 = new Gtk.HBox();
            this.hbox21.Name = "hbox21";
            this.hbox21.Spacing = 6;
            // Container child hbox21.Gtk.Box+BoxChild
            this.label18 = new Gtk.Label();
            this.label18.WidthRequest = 100;
            this.label18.Name = "label18";
            this.label18.Xalign = 1F;
            this.label18.LabelProp = "Last frame:";
            this.hbox21.Add(this.label18);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox21[this.label18]));
            w34.Position = 0;
            w34.Expand = false;
            w34.Fill = false;
            // Container child hbox21.Gtk.Box+BoxChild
            this.eLastFrame = new Gtk.Entry();
            this.eLastFrame.TooltipMarkup = "Last frame in the range of frames to be rendered, e.g. '500'";
            this.eLastFrame.CanFocus = true;
            this.eLastFrame.Name = "eLastFrame";
            this.eLastFrame.IsEditable = true;
            this.eLastFrame.InvisibleChar = '●';
            this.hbox21.Add(this.eLastFrame);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox21[this.eLastFrame]));
            w35.Position = 1;
            this.vbox13.Add(this.hbox21);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox13[this.hbox21]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            this.alignment19.Add(this.vbox13);
            this.frame6.Add(this.alignment19);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = "<b>Frame range</b>";
            this.GtkLabel3.UseMarkup = true;
            this.frame6.LabelWidget = this.GtkLabel3;
            this.alignmentFrames.Add(this.frame6);
            this.vboxWindow.Add(this.alignmentFrames);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vboxWindow[this.alignmentFrames]));
            w40.Position = 3;
            w40.Expand = false;
            w40.Fill = false;
            // Container child vboxWindow.Gtk.Box+BoxChild
            this.alignmentButtons = new Gtk.Alignment(1F, 0.7F, 0F, 0F);
            this.alignmentButtons.Name = "alignmentButtons";
            this.alignmentButtons.BorderWidth = ((uint)(13));
            // Container child alignmentButtons.Gtk.Container+ContainerChild
            this.hboxButtons = new Gtk.HBox();
            this.hboxButtons.Name = "hboxButtons";
            this.hboxButtons.Spacing = 6;
            // Container child hboxButtons.Gtk.Box+BoxChild
            this.hbox10 = new Gtk.HBox();
            this.hbox10.Name = "hbox10";
            this.hbox10.Spacing = 6;
            // Container child hbox10.Gtk.Box+BoxChild
            this.btnCancel = new Gtk.Button();
            this.btnCancel.TooltipMarkup = "Close this window and discard changes.";
            this.btnCancel.WidthRequest = 100;
            this.btnCancel.HeightRequest = 35;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseUnderline = true;
            // Container child btnCancel.Gtk.Container+ContainerChild
            Gtk.Alignment w41 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w42 = new Gtk.HBox();
            w42.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w43 = new Gtk.Image();
            w43.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            w42.Add(w43);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w45 = new Gtk.Label();
            w45.LabelProp = "Cancel";
            w45.UseUnderline = true;
            w42.Add(w45);
            w41.Add(w42);
            this.btnCancel.Add(w41);
            this.hbox10.Add(this.btnCancel);
            Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.hbox10[this.btnCancel]));
            w49.Position = 0;
            w49.Expand = false;
            w49.Fill = false;
            w49.Padding = ((uint)(5));
            // Container child hbox10.Gtk.Box+BoxChild
            this.btnSave = new Gtk.Button();
            this.btnSave.TooltipMarkup = "Save this job and add it to the job queue.";
            this.btnSave.WidthRequest = 100;
            this.btnSave.CanFocus = true;
            this.btnSave.Name = "btnSave";
            this.btnSave.UseUnderline = true;
            // Container child btnSave.Gtk.Container+ContainerChild
            Gtk.Alignment w50 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w51 = new Gtk.HBox();
            w51.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w52 = new Gtk.Image();
            w52.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-floppy", Gtk.IconSize.Menu, 16);
            w51.Add(w52);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w54 = new Gtk.Label();
            w54.LabelProp = "Save";
            w54.UseUnderline = true;
            w51.Add(w54);
            w50.Add(w51);
            this.btnSave.Add(w50);
            this.hbox10.Add(this.btnSave);
            Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.hbox10[this.btnSave]));
            w58.Position = 1;
            w58.Expand = false;
            w58.Fill = false;
            w58.Padding = ((uint)(5));
            this.hboxButtons.Add(this.hbox10);
            Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.hboxButtons[this.hbox10]));
            w59.Position = 0;
            w59.Expand = false;
            w59.Fill = false;
            this.alignmentButtons.Add(this.hboxButtons);
            this.vboxWindow.Add(this.alignmentButtons);
            Gtk.Box.BoxChild w61 = ((Gtk.Box.BoxChild)(this.vboxWindow[this.alignmentButtons]));
            w61.Position = 4;
            w61.Expand = false;
            w61.Fill = false;
            this.alignmentWindow.Add(this.vboxWindow);
            this.Add(this.alignmentWindow);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 624;
            this.DefaultHeight = 489;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.btnCancel.Clicked += new System.EventHandler(this.OnBtnCancelClicked);
            this.btnSave.Clicked += new System.EventHandler(this.OnBtnSaveClicked);
        }
    }
}
