// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace loki {
    
    
    public partial class GruntWin {
        
        private Gtk.Alignment alignment5;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label1;
        
        private Gtk.Label lblConnection;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label2;
        
        private Gtk.Label lblStatus;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.ProgressBar pb1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget loki.GruntWin
            this.Name = "loki.GruntWin";
            this.Title = "Loki grunt";
            this.Icon = Gdk.Pixbuf.LoadFromResource("16x16.png");
            // Container child loki.GruntWin.Gtk.Container+ContainerChild
            this.alignment5 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.alignment5.BorderWidth = ((uint)(20));
            // Container child alignment5.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.WidthRequest = 100;
            this.label1.Name = "label1";
            this.label1.Xalign = 1F;
            this.label1.LabelProp = "Connection:";
            this.hbox3.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.lblConnection = new Gtk.Label();
            this.lblConnection.TooltipMarkup = "Current status of connection with the master.";
            this.lblConnection.Name = "lblConnection";
            this.lblConnection.Xalign = 0F;
            this.lblConnection.LabelProp = "searching for master...";
            this.hbox3.Add(this.lblConnection);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.lblConnection]));
            w2.Position = 1;
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.WidthRequest = 100;
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = "My status:";
            this.hbox4.Add(this.label2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox4[this.label2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.lblStatus = new Gtk.Label();
            this.lblStatus.TooltipMarkup = "Am I busy running a task, or idle?";
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Xalign = 0F;
            this.lblStatus.LabelProp = "idle";
            this.hbox4.Add(this.lblStatus);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox4[this.lblStatus]));
            w5.Position = 1;
            this.vbox2.Add(this.hbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(25));
            this.alignment1.TopPadding = ((uint)(12));
            this.alignment1.RightPadding = ((uint)(25));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.pb1 = new Gtk.ProgressBar();
            this.pb1.TooltipMarkup = "Visual indicator of status: moves when I'm running a task.";
            this.pb1.HeightRequest = 10;
            this.pb1.Name = "pb1";
            this.alignment1.Add(this.pb1);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            this.alignment5.Add(this.vbox2);
            this.Add(this.alignment5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 420;
            this.DefaultHeight = 108;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
